### ISSUE TITLE
Error initiating IAR toolchain backend. Some functionality may be unavailable: Service registry exited prematurely, code: 1

### ISSUE THREAD

**Issue by Anc9** [IARSystems/iar-vsc-build#82] opened 2024-08-02 07:33 UTC
**Describe the bug:**
This error occurs when I open the iar project on vscode, resulting in the files directory in iAR-build not being displayed. I have looked up some other bugs, but no similar problem has occurred, please help me confirm what is the problem?I tried to reinstall iar and vscode, but it still didn't work. The iar version is 9.30.1
The following is the output of IarServiceslauncher
![c830a8f83dfb5f2a4b3792ea88487dd](https://github.com/user-attachments/assets/17e94ab3-52f8-4f40-9f7b-66febb9f4ab9)
![image](https://github.com/user-attachments/assets/98b7246b-d20f-4fea-a9b7-660645a1d2ac)

**Comment by mario-pi** [comment] 2024-08-02 10:31
Thanks for reporting this issue. There seems to be a problem with how the .json files are read from the service launcher utility.
Could you please provide more details about your system configuration (including the system OS and its version, language and locale settings), so that we can try to reproduce this?

**Comment by Anc9** [comment] 2024-08-03 02:22
Thank you for your reply. My system is win10 and the language is Chinese. I would like to add that every time I reinstall iar, the file view can be displayed normally when I open an iar project using vscode for the first time, but when I close vscode, I open the same iar project again. The above problems arise. Thanks for your reply and have a great weekend.
Below is my version of windows：（By the way, both my vscode and iar-build extensions are the latest versions）
![image](https://github.com/user-attachments/assets/52130c48-81f5-447b-b869-393439885205)

**Comment by Anc9** [comment] 2024-08-28 12:10
Thanks for your reply, I think I found the problem, due to the company, after I open this json file, the computer I work on encrypts the json file, which causes the next time I open the vscode again, it looks like the iar expansion plugin can't read this file, so this problem occurs!

**Comment by mario-pi** [comment] 2024-08-29 08:12
Thanks for following up on this. As the issue is not directly related to the VSCode plugins, you should either report this to your IT department or to the IAR technical support, so that we can know more details about your configuration.

Closing.

**Closed by mario-pi** 2024-08-29 08:12 UTC
Labels: bug
