### ISSUE TITLE
Use ninja.exe directly rather than IarBuild for build tasks

### ISSUE THREAD

**Issue by mitch-johnson-ik** [IARSystems/iar-vsc-build#31] opened 2022-10-11 17:07 UTC
The default build tasks that wrap IarBuild.exe are inefficient, and do not take full advantage of system resources even when utilizing `-parallel`. On an example project on a Windows 10 VM under Parallels Desktop, a project built with IarBuild takes 40+ seconds to build using anything over 4 threads and uses ~50% CPU.

When using a custom build task that first invokes `IarBuild.exe PROJECTFILE -ninja debug`, then `ninja.exe` to build, the same build executes in <15 seconds.

In order to get a reasonable textual build output, I need to set the following environment variables on the build task:
```
"env": {
	"QCCARM": "--silent",
	"IASMARM": "-S",
	"ILINKARM_CMD_LINE": "--silent",
}
```

It seems the `$iar-cc` problem matcher does not match problems in the build output, though.

**Comment by jlonnberg** [comment] 2023-03-28 06:32
Closing as duplicate of #42

**Closed by jlonnberg** 2023-03-28 06:32 UTC
Labels: enhancement
