### ISSUE TITLE
IAR Build Utility starts automatically and uses 100% processor

### ISSUE THREAD

**Issue by JanWielgus** [IARSystems/iar-vsc-build#48] opened 2023-05-12 08:10 UTC
I have a problem with the newest version (v1.20.3). When I open the IAR project in VS Code and click on the IAR icon on the left panel, in about 10 seconds this extension opens ~30 _IAR Build Utility_ processes out of nowhere, that uses in total 100% of the processor. I waited for about 30 minutes, but nothing happens and PC is barely usable.
In Task Manager it looks like this:
![image](https://github.com/IARSystems/iar-vsc-build/assets/26146666/7ac78971-7d33-4097-becb-889c02f27e5d)

I have IAR Embedded Workbench 8.3
Everything works on version 1.20.2 and 1.20.1 (those versions I tested)

Thank you for your help!

**Comment by jlonnberg** [comment] 2023-05-12 10:11
@JanWielgus Can you please describe your project structure, e.g., number of .ewp files in the opened folder, number of configurations and number of files in the project? I suspect that this is part of the system that handles underlying information which basically runs a series to builds to gather enough information, so if the folder contains many ewp-files and/or projects with many files we might have a problem there.

**Comment by JanWielgus** [comment] 2023-05-15 17:53
@jlonnberg In opened folder I have indeed about 200 .ewp files, each of them have at least two configurations and many have four. Many projects are quite big.
Can something be done with this?

**Comment by HampusAdolfsson** [comment] 2023-05-16 06:58
Hi, I just answered someone else with the same problem in another issue. See my reply here:
https://github.com/IARSystems/iar-vsc-build/issues/49#issuecomment-1547673666

**Comment by jlonnberg** [comment] 2023-05-22 15:00
Closing as duplicate of #49

**Closed as not planned by jlonnberg** 2023-05-22 15:00 UTC
Labels: bug
