### ISSUE TITLE
Project parsing on Linux

### ISSUE THREAD

**Issue by axel-lebourhis** [IARSystems/iar-vsc-build#18] opened 2022-07-25 22:22 UTC
Hi all !

I'm currently evaluating the feasibility of developing with IAR projects under a Linux environment.
I gave a try to BX and I really like it, the build performances  are great, it's lightning fast compared to my windows env.
It also integrates well in VSCode.

But, not being able to render the project files in the view is a huge drawback for me, it makes everything painful (searching for files, modifying the project...)

In my opinion, this extension needs to provide more compatibility with Linux to really take advantage of BX from a developer perspective.

Hope something can be done ! :)

**Comment by mario-pi** [comment] 2022-08-02 14:45
Thanks for reporting this feature request. This is currently caused by BXARM releases not containing any IDE components, including project manipulation support.
I will report this as an internal feature request and close this issue.

**Closed by mario-pi** 2022-08-02 14:45 UTC
