### ISSUE TITLE
Build tasks do not start

### ISSUE THREAD

**Issue by jofa-ph** [IARSystems/iar-vsc-build#59] opened 2023-08-21 14:20 UTC
When triggering a build task from the toolbar, execution does not start. A terminal opens saying ` *  Executing task: iar: Build Project `. Nothing else will appear in that terminal. I checked the extension's output: nothing. Only the extension host output gives a potential hint: `2023-08-21 16:15:19.702 [error] Error: ENOENT: no such file or directory, open 'C:\Users\320007677\AppData\Local\Temp\iar-build\7bbcfc69-ec75-49df-99d2-b526880d207d.custom_argvars'`

The bug appears when working remotely as well as locally to the build PC.
- Workbench version: 8.5 (RL78)
- Extension version: v1.30.2

**Comment by jlonnberg** [comment] 2023-08-22 06:41
Hi @jofa-ph
I've done a quick test on my dev-machine and it worked as intended, but I'm going to test this on a clean machine as well. It would be great if you could provide:

- The OS and version you're using.
- The active version of VsCode.
- Installation path to the workbench.

**Comment by jlonnberg** [comment] 2023-08-22 11:44
Problem seems to be that vscode fails to write to a non-existant folder. As a WA, create a folder named "iar-build" in C:\Users\320007677\AppData\Local\Temp\ and we'll fix this in the upcoming release

**Comment by jlonnberg** [comment] 2023-08-22 15:09
Duplicate of #58

**Closed by jlonnberg** 2023-08-22 15:09 UTC
Labels: bug
